#!/bin/sh

# Shove all workspaces onto the main screen
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

# Launch just the default bar
pkill polybar
while pgrep polybar >/dev/null; do sleep 0.1; done
polybar main & disown