# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot = {
    # Use the systemd-boot EFI boot loader.
    loader.systemd-boot.enable = true;
    loader.systemd-boot.editor = false; # editor defeats the purpose of all security...
    loader.efi.canTouchEfiVariables = true;

    initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" 
  "sd_mod" "bbswitch"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];

    # boot niceties
    cleanTmpDir = true;
    consoleLogLevel = 3;
    # splash screen
    plymouth = {
      enable = true;
    };
  };

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-uuid/F3E8-3D3D";
      fsType = "vfat";
    };
    "/" = {
      device = "/dev/disk/by-label/root";
      fsType = "ext4";
    };
    "/home" = {
      device = "/dev/disk/by-label/home";
      fsType = "ext4";
    };
  };

  swapDevices = [
    { label = "swap"; }
  ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.nvidiaOptimus.disable = true;
  hardware.opengl.extraPackages = [pkgs.linuxPackages.nvidia_x11.out];
  hardware.opengl.extraPackages32 = 
[pkgs.linuxPackages.nvidia_x11.lib32];

  services.undervolt = {
    enable = true;
    coreOffset = "-110";
    gpuOffset = "-110";
  };
}
