#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 3
bspc config window_gap 15

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
# bspc config focus_follows_pointer true
# bspc config pointer_follows_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Panel & borders
bspc config top_padding 30
# bspc config right_padding 5
# bspc config left_padding 5
# bspc config bottom_padding 5
# bspc config normal_border_color "#A8896C"
#bspc config active_border_color "#47E4E0"
# bspc config focused_border_color "#47E4E0"

# Use background image color scheme
~/.config/bspwm/apply-colors.sh

bspc rule -a '*:zathura' state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Xfce4-panel state=floating
bspc rule -a polybar state=floating
bspc rule -a Docky state=floating layer=above
bspc rule -a Plank state=floating layer=above
# bspc rule -a Subl3 state=tiled
bspc rule -a Galculator state=floating
# bspc rule -a plasmashell state=floating
bspc rule -a "Wrapper-1.0" border=off focus=on follow=on # manage=off # Whisker Menu
bspc rule -a Oblogout state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Emacs state=tiled
bspc rule -a ".wpg-wrapped" state=floating
bspc rule -a "Gcolor3" state=floating

# For wine games, don't fullscreen inside app, use the bspwm rule :P
bspc rule -a "osu!.exe" state=fullscreen

# BSPWM-specific autostart
export MOZ_USE_XINPUT2=1
export SXHKD_SHELL=/bin/sh
sxhkd &
exec ~/bin/autostart.sh
