#!/bin/sh

# Split workspaces between the monitors
bspc monitor eDP1  -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 0

# Launch both bars
pkill polybar
while pgrep polybar >/dev/null; do sleep 0.1; done
polybar main & disown
polybar second & disown